// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static String webApiKey = dotenv.get("FIREBASE_WEB_API_KEY");
  static String androidApiKey = dotenv.get("FIREBASE_ANDROID_API_KEY");

  static FirebaseOptions web = FirebaseOptions(
    apiKey: webApiKey,
    appId: '1:209237093143:web:22e87e7a602f1c49956552',
    messagingSenderId: '209237093143',
    projectId: 'minto-7229a',
    authDomain: 'minto-7229a.firebaseapp.com',
    storageBucket: 'minto-7229a.appspot.com',
    measurementId: 'G-8PV9BSEQCN',
  );
  static FirebaseOptions android = FirebaseOptions(
    apiKey: androidApiKey,
    appId: '1:209237093143:android:5da759686bb41a04956552',
    messagingSenderId: '209237093143',
    projectId: 'minto-7229a',
    storageBucket: 'minto-7229a.appspot.com',
  );
}
